"""
DC Capacity Forecasting — Dashboard Data Export
=================================================
Reads the finished Excel workbook (outputs/DC_Capacity_Forecast.xlsx) and
embeds its contents directly into dashboard/index.html as
window.NOVACART_DATA, plus inlines the vendored Chart.js and SheetJS
libraries -- a single, fully self-contained HTML file with ZERO external
network dependencies.

An optional "Reload live from Excel" button in the dashboard re-parses the
.xlsx directly via SheetJS when the project is served over http/https.

Author: Milad Shabani
"""

import json
import re
import numpy as np
import pandas as pd
from datetime import datetime
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
VENDOR_DIR = os.path.join(SCRIPT_DIR, "vendor")

WORKBOOK_PATH = os.path.join(PROJECT_ROOT, "outputs", "DC_Capacity_Forecast.xlsx")
DASHBOARD_HTML_PATH = os.path.join(PROJECT_ROOT, "dashboard", "index.html")
OUT_PATH = os.path.join(PROJECT_ROOT, "dashboard", "data.js")

HEADER_ROW_0INDEXED = {
    "On-Time Delivery Rate": 3, "Staff Reallocation Plan": 2, "Validation - Backtest": 2,
    "Backtest Daily Trend": 2, "Undelivered at Horizon End": 2, "Multi-DC What-If Comparison": 2,
}


def read_sheet(sheet_name):
    header = HEADER_ROW_0INDEXED.get(sheet_name, 0)
    df = pd.read_excel(WORKBOOK_PATH, sheet_name=sheet_name, header=header, engine="openpyxl")
    df = df.dropna(how="all")
    return df


def to_records(df):
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = df[col].dt.strftime("%Y-%m-%d")
    df = df.replace({np.nan: None})
    return df.to_dict(orient="records")


def main():
    print("Reading workbook sheets...")
    forecast = read_sheet("Forecast Output")
    net_daily = read_sheet("Network Daily Summary")
    dc_monthly = read_sheet("DC Monthly Summary")
    at_risk = read_sheet("At-Risk DCs")
    surplus = read_sheet("Surplus Capacity DCs")
    risk_by_type = read_sheet("Risk by Service Type")
    region = read_sheet("Region Summary")
    on_time = read_sheet("On-Time Delivery Rate")
    realloc = read_sheet("Staff Reallocation Plan")
    backtest_summary = read_sheet("Validation - Backtest")
    backtest_summary = backtest_summary[backtest_summary["MAE"].notna()].reset_index(drop=True)
    backtest_daily = read_sheet("Backtest Daily Trend")
    undelivered = read_sheet("Undelivered at Horizon End")
    multi_scenario = read_sheet("Multi-DC What-If Comparison")

    # Network-wide on-time rate, parsed back out of the sheet's title line
    wb_raw = pd.read_excel(WORKBOOK_PATH, sheet_name="On-Time Delivery Rate", header=None, nrows=1)
    title_text = str(wb_raw.iloc[0, 0])
    m = re.search(r"([\d.]+)%", title_text)
    network_on_time_rate = float(m.group(1)) if m else None

    data = {
        "Forecast": to_records(forecast),
        "NetworkDaily": to_records(net_daily),
        "DCMonthly": to_records(dc_monthly),
        "AtRisk": to_records(at_risk),
        "Surplus": to_records(surplus),
        "RiskByType": to_records(risk_by_type),
        "Region": to_records(region),
        "OnTimeByDC": to_records(on_time),
        "NetworkOnTimeRate": network_on_time_rate,
        "Reallocation": to_records(realloc),
        "BacktestSummary": to_records(backtest_summary),
        "BacktestDaily": to_records(backtest_daily),
        "Undelivered": to_records(undelivered),
        "MultiScenario": to_records(multi_scenario),
        "_meta": {
            "generatedAt": datetime.now().isoformat(timespec="seconds"),
            "sourceWorkbook": "DC_Capacity_Forecast.xlsx",
        },
    }

    for k, v in data.items():
        if isinstance(v, list):
            print(f"  {k:16s} -> {len(v)} records")

    js_content = (
        "// AUTO-GENERATED by scripts_dashboard/export_dashboard_data.py -- do not edit by hand.\n"
        "// Build-time snapshot of DC_Capacity_Forecast.xlsx so the dashboard works offline\n"
        "// with a plain double-click (no local server required).\n"
        "window.NOVACART_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)
    size_kb = len(js_content.encode("utf-8")) / 1024
    print(f"\nWrote {OUT_PATH} ({size_kb:.0f} KB) [reference export, not required by the dashboard]")

    with open(DASHBOARD_HTML_PATH, "r", encoding="utf-8") as f:
        html = f.read()

    inline_data_script = (
        '<script id="novacart-embedded-data">\n'
        "window.NOVACART_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
        "</script>"
    )
    pattern = re.compile(r'<script id="novacart-embedded-data">.*?</script>', re.S)
    if not pattern.search(html):
        raise RuntimeError('Could not find the <script id="novacart-embedded-data"> placeholder in dashboard/index.html.')
    html = pattern.sub(lambda m: inline_data_script, html, count=1)

    def inline_vendor(html_text, placeholder_id, vendor_filename):
        vendor_path = os.path.join(VENDOR_DIR, vendor_filename)
        with open(vendor_path, "r", encoding="utf-8") as vf:
            lib_code = vf.read()
        pat = re.compile(r'<script id="' + re.escape(placeholder_id) + r'">.*?</script>', re.S)
        if not pat.search(html_text):
            raise RuntimeError(f'Could not find placeholder <script id="{placeholder_id}"> in dashboard/index.html.')
        replacement = f'<script id="{placeholder_id}">\n{lib_code}\n</script>'
        return pat.sub(lambda m: replacement, html_text, count=1)

    html = inline_vendor(html, "vendor-chartjs", "chart.umd.js")
    html = inline_vendor(html, "vendor-xlsx", "xlsx.full.min.js")

    with open(DASHBOARD_HTML_PATH, "w", encoding="utf-8") as f:
        f.write(html)

    html_size_kb = len(html.encode("utf-8")) / 1024
    print(f"Embedded dataset + Chart.js + SheetJS directly into {DASHBOARD_HTML_PATH} ({html_size_kb/1024:.2f} MB total)")
    print("This file now has ZERO external network dependencies -- it works fully offline.")


if __name__ == "__main__":
    main()
